name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  # Publish `v1.2.3` tags as releases.
  # tags:
  #   - v*
  # # Run tests for any PRs.
  # pull_request:
  
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  init-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js 12.20.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.1'
      - name: Install yarn and run test
        run: |  
          yarn
          yarn test

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-publish:
    # Ensure test job passes before pushing image.
    needs: init-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      # - name: Build and push container image to Github Packages
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository: ${{ github.repository }}/bluesky-react-sample-app
      #     tag_with_sha: true
      #     tag_with_ref: true
      - name: Build and push container image to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: enpapex/bluesky-react-sample-app
          tag_with_sha: true
          tag_with_ref: true
      

