name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  # Publish `v1.2.3` tags as releases.
  # tags:
  #   - v*
  # # Run tests for any PRs.
  # pull_request:

env:
  IMAGE_NAME: bluesky-sample

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.20.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.1'
      - name: Install yarn and run test
        run: |  
          yarn
          yarn test

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push_to_registry:
    needs: test
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: robincher/bluesky-react-sample-app/$IMAGE_NAME
          tag_with_ref: true
